# Generated by Django 3.2.7 on 2021-09-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='post',
        ),
    ]
